#!/usr/bin/perl -w

use strict;
use esmith::Build::CreateLinks qw(:all);


my @templates = qw(
    /etc/amavisd.conf
    /etc/postfix/main.cf
    /etc/postfix/master.cf
    /etc/cron.d/sa-update
    /etc/dovecot/sieve-scripts/before.sieve
);

#
# nethserver-mail-filter-UPDATE event
#

event_templates('nethserver-mail-filter-update', @templates);

event_actions('nethserver-mail-filter-update',
	      'initialize-default-databases' => '00',
	      'nethserver-mail-filter-conf' => '20',	      
	      'nethserver-mail-sieve-compile' => '30',
	      'firewall-adjust' => '40',
	      'runlevel-adjust' => '50');

event_services('nethserver-mail-filter-update',
	       'amavisd' => 'restart',
	       'postfix' => 'restart',
               'dovecot' => 'restart');


#
# nethserver-mail-filter-SAVE event
#

event_templates('nethserver-mail-filter-save', qw(
    /etc/amavisd.conf
    /etc/dovecot/sieve-scripts/before.sieve
));

event_services('nethserver-mail-filter-save',
	       'amavisd' => 'reload',
               'dovecot' => 'reload');
