#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use NethServer::Service;
use esmith::ConfigDB;
use strict;

my @services = ('clamd');

NethServer::Service::manage_remove('nethserver-mail-filter',
				   @services);



my $configDb = esmith::ConfigDB->open() || die('Could not open Config DB');
my $autoConfig = $configDb->get_prop('amavisd', 'AutoConfigStatus');

if(defined $autoConfig && $autoConfig ne 'enabled') {
    # Manual configuration: quit here.
    exit 0;
}

my $contentInspectionType = $configDb->get_prop('amavisd', 'ContentInspectionType');

# Disable anti-spam and anti-virus checking:
$configDb->set_prop('amavisd', 'VirusCheckStatus', 'disabled');
$configDb->set_prop('amavisd', 'SpamCheckStatus', 'disabled');

if($contentInspectionType ne 'after-queue') {
    # Switch back to postfix AFTER-QUEUE content filtering:
    $configDb->set_prop('amavisd', 'ContentInspectionType', 'after-queue');
    $configDb->set_prop('postfix', 'ConnectionsLimit', '');
    $configDb->set_prop('postfix', 'ConnectionsLimitPerIp', '');
}

