#!/usr/bin/perl

#
# nethserver-mail-smtpd-connections -- Adjust postfix smtpd
# connections limit, if it has not already done
#
# Copyright (C) 2012 Nethesis srl
#

use esmith::ConfigDB;
use strict;


my $configDb = esmith::ConfigDB->open() || die('Could not open Config DB');

my $connectionsLimit = undef;
my $connectionsLimitPerIp = undef;

if($configDb->get_prop('amavisd', 'ContentInspectionType') eq 'before-queue') {
    $connectionsLimit = 20;
    $connectionsLimitPerIp = 10;
} elsif($configDb->get_prop('amavisd', 'ContentInspectionType') eq 'after-queue') {
    $connectionsLimit = 0;
    $connectionsLimitPerIp = 0;
}

if(defined $connectionsLimit && $configDb->get_prop('postfix', 'ConnectionsLimit') eq '') {
    $configDb->set_prop('postfix', 'ConnectionsLimit', $connectionsLimit);
}

if(defined $connectionsLimitPerIp && $configDb->get_prop('postfix', 'ConnectionsLimitPerIp') eq '') {
    $configDb->set_prop('postfix', 'ConnectionsLimitPerIp', $connectionsLimitPerIp);
}

