#!/usr/bin/perl

#
# nethserver-mail-filter-conf 
#
# Copyright (C) 2012 Nethesis srl
#

use NethServer::Service;
use File::Path;
use esmith::ConfigDB;
use User::pwent;
use strict;


#
# Announce clamd dependency
#

my @services = ('clamd');

NethServer::Service::manage_add('nethserver-mail-filter', @services);

#
# Adjust postfix smtpd connections limit, if it has not already done
#

my $configDb = esmith::ConfigDB->open() || die('Could not open Config DB');

my $connectionsLimit = $configDb->get_prop('postfix', 'ConnectionsLimit');
my $autoConfig = $configDb->get_prop('amavisd', 'AutoConfigStatus');

if(defined $autoConfig && $autoConfig ne 'enabled') {
    # Manual configuration: quit here.
    exit 0;
}

my $contentInspectionType = $configDb->get_prop('amavisd', 'ContentInspectionType');

# Enable anti-spam and anti-virus checking:
$configDb->set_prop('amavisd', 'VirusCheckStatus', 'enabled');
$configDb->set_prop('amavisd', 'SpamCheckStatus', 'enabled');

if($contentInspectionType ne 'before-queue') {
    # Switch to postfix BEFORE-QUEUE content filtering:
    $configDb->set_prop('amavisd', 'ContentInspectionType', 'before-queue');
    $configDb->set_prop('postfix', 'ConnectionsLimit', 20);
    $configDb->set_prop('postfix', 'ConnectionsLimitPerIp', 10);
}


