#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use User::pwent;

# Refs #2093 -- Adjust amavis home dir permissions to allow clamd to
# scan attachments:
my $amavisPw = getpwnam('amavis') || die("Could not find amavis user");
chmod(0750, $amavisPw->dir);
chmod(0750, $amavisPw->dir . '/tmp');

# Refs #2093 -- Add clam user into amavis group (requires clamd
# restart)
system(qw(/usr/sbin/usermod -G amavis -a clam));


