#!/usr/bin/perl -w
#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use esmith::ConfigDB;
my $db = esmith::ConfigDB->open_ro or die "[ERROR] Impossible to open the Configuration database";
my $spamEnable = $db->get_prop('rspamd','SpamCheckStatus') || 'enabled';

exit 0 unless ( $spamEnable eq 'disabled');

opendir my $dir, "/etc/rspamd/modules.d" or die "[ERROR] Cannot open directory: $!";
my @files = readdir $dir;
closedir $dir;

foreach my $file (@files) {
#antivirus.conf is handled by its status
#multimap manages white/blacklist and file extension
next if (($file eq '.') || 
    ($file eq '..') || 
    ($file eq 'antivirus.conf') || 
    ($file eq 'multimap.conf'));

open my $fh, ">", "/etc/rspamd/local.d/$file" or die("[ERROR] Could not open file. $!");
print $fh "#Disabled by The nethgui UI\nenabled = false";
close $fh
}
