#!/bin/bash
#
#	/etc/rc.d/init.d/spfd
#
#       Sender Policy Framework (SPF)
#	is an email validation system designed to prevent email spam
#	by detecting email spoofing, a common vulnerability, by
#	verifying sender IP addresses
#

# chkconfig: 2345 70 20
# description: Sender Policy Framework (SPF)
#
### BEGIN INIT INFO
# Provides:       spfd
# Required-Start: $
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Sender Policy Framework (SPF)
### END INIT INFO

# Source function library.
. /etc/init.d/functions

servicename=spfd
pidfile=/var/run/${servicename}.pid
codefile=/usr/share/doc/perl-Mail-SPF-2.007/sbin/spfd

user=${servicename}
group=${servicename}
socket=/var/run/${servicename}.sock

start() {
    local retval
    echo -n "Starting $servicename: "
    daemon --pidfile=${pidfile} /usr/bin/perl ${codefile} \
	--socket ${socket} \
	--set-user ${user} \
	--set-group ${group} \
    
    retval = $?
    touch /var/lock/subsys/${servicename}
    return $retval	
}	

stop() {
    local retval
    echo -n "Shutting down $servicename: "
    killproc -p ${pidfile} ${servicename}
    retval = $?
    rm -f /var/lock/subsys/${servicename}
    return $retval
}

restart() {
    stop
    start
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status -p $pidfile $servicename
	;;
    restart)
	restart
	;;
    reload)
	restart
	;;
    condrestart)
	[ -f /var/lock/subsys/${servicename} ] && restart || :
	;;
    *)
	echo "Usage: $servicename {start|stop|status|reload|restart}"
	exit 1
	;;
esac
exit $?
